apiVersion: v1
kind: Pod
metadata:
  name: greg-pod
  labels:
    pod-selector: main-pod-selector
spec:
  containers:
    - name: training-application
      image: 651828462322.dkr.ecr.eu-west-3.amazonaws.com/node-web-app:latest
      # env:
      #   - name: AUTHOR
      #     valueFrom:
      #       configMapKeyRef:
      #         name: greg-configmap
      #         key: author
      envFrom:
        - configMapRef:
            name: greg-configmap
      # Taking random values from kubernetes docs.
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
